title = 'Clojure Mini Applications Step by Step'
baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
# wordt via modules geladen
# theme = "papercss-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"
paginate = 5

[privacy.disqus]
disable = true

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99

[params]
homeMetaContent = "A Hugo theme made with PaperCSS, the less formal CSS framework."
dateFormat = "Jan 2, 2006"
navTitleLink = "/"

[[menu.nav]]
name = "Blog"
url = "/"
weight = 1

#Pascal : geen "Tags" Menu
#[[menu.nav]]
#name = "Tags"
#url = "/tags/"
#weight = 2

[[menu.nav]]
name = "About"
url = "/about/"
weight = 3

# Pascal : geen "RSS" menu
#[[menu.nav]]
#name = "RSS"
#url = "/index.xml"
#weight = 4

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2

# Pascal 12/03/2022 - nodig voor bare-min theme
# (na aanpassing dan "hugo mod tidy" uitvoeren
[module]
#  [module.hugoVersion]
#    min = "0.73.0"
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
#    path = "github.com/kaushalmodi/hugo-bare-min-theme"
#    path = "github.com/zwbetz-gh/papercss-hugo-theme"
